apiVersion: v2
name: k8s-image-swapper
description: Mirror images into your own registry and swap image references automatically.
type: application
version: 1.11.0
appVersion: 1.5.10
home: https://github.com/estahn/charts/tree/main/charts/k8s-image-swapper
keywords:
  - kubernetes
  - kubernetes-webhook
  - golang
  - mutating-webhook
maintainers:
  - email: enrico.stahn@gmail.com
    name: estahn
annotations:
  artifacthub.io/changes: |
    - "Allow cert-manager certs to be issued by a cluster issuer"
  artifacthub.io/images: |
    - name: k8s-image-webhook
      image: ghcr.io/estahn/k8s-image-swapper:1.5.10
